name: "CD Pipeline"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Deploy project over SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd atteny-backend && git pull && systemctl daemon-reload && \
            cd sheet-server && /root/.local/share/pnpm/pnpm install && /root/.local/share/pnpm/pm2 restart server.mjs